### ISSUE TITLE
Cycada/Cider?

### ISSUE THREAD

**Issue by upintheairsheep** [columbia/PrivateKube#3]
Can you release the software on GitHub with source code, documentation, packages, tutorial on installing .ipa files, upload the ipa files you extracted to archive.org, and the shortcut and ciderpress .apks? And the closed source frameworks from apple put it on Acrhive.org, which is excluded from most copyright. If you are concerned about copyright to a big extent, email the files to kayvonkamyar@gmail.com, which i will manage copyright and if Apple sues me, i will manage it.

https://systems.cs.columbia.edu/projects/cycada/
https://systems.cs.columbia.edu/files/wpid-asplos2014-cider.pdf

**Comment by upintheairsheep** [comment]
The software is about 8 years old now. Releasing it would be good for future contributions. I was searching and contacting for this program for about a month now.

**Comment by tholop** [comment]
Sorry, I can't help about that project, which is not related to PrivateKube.
